### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by marksuarez** [darkwhispering/Advanced-Browser-Check#14]
Hi there, 
Update 4.4.0 caused an error when i tried to update it (2016 august 22 11:40am). Im on Wordpress 4.5.3

`Parse error: syntax error, unexpected '=', expecting ')' in .../wp-content/plugins/advanced-browser-check/abc-core.php on line 105`

apologies if this

**Comment by darkwhispering** [comment]
Thanks for reporting @marksuarez 
This issues slipped through my testing yesterday, sry for that.

The issue has been fixed and v4.4.1 should be available at any time now.
