### ISSUE TITLE
customize the messages(html support)

### ISSUE THREAD

**Issue by yylzcom** [darkwhispering/Advanced-Browser-Check#2]
Hi, I need to customize the message so that I can add QR code or links. I think (html code support is best solution at all)

Would you please add this feature? 

Thanks!

**Comment by darkwhispering** [comment]
Hi

Not at the moment, but I will keep it in mind for the future.

**Comment by darkwhispering** [comment]
You can use HTML code in the message field on the settings page to style the text or add images using the <img> tag.
